---
title: "My Blog"
sidebar: false 
---

# My Experiences in Erasmus from Medium

Merhabalar! Öncelikle bu yazıyı okuyorsanız Erasmus'un ne demek olduğunu ve başınızdan geçmiş/geçecek olan süreçlere de aşinasınızdır diye düşünüyorum çünkü ben bunlardan bahsetmeyeceğim.

Ben bu yazımda size daha spesifik ve pratik bir bakış açısıyla gittiğim üniversiteden, kaldığım yurttan ve yaptığım gezilerden bilgi aktarmayı tercih ediyorum. Üstelik kendi Erasmus deneyimimden önce de madde madde yazılan deneyimleri okumayı daha elverişli bulduğumdan yazımın devamı da o şekilde olacak.

**EĞİTİM:** Öncelikle Erasmus'a 2021--2022 bahar döneminde Polonya'nın Lodz şehrinde bulunan Lodz Üniversitesi'ne gittim. Lodz Üniversitesi bahar dönemini korona ne kadar etkisini yitirmiş olsa da online olarak devam ettirmeyi tercih etti. Toplam aldığım 5 ders vardı, kendi üniversitemde de yani Hacettepe Üniversitesi'nde de hepsini zorunlu seçmeli olarak eşleştirdim. 4 dersten de geçtim(geçemediğimi de hocanın işgüzarlığına veriyorum. Derslere girmiyordu...)

Genel anlamıyla dersler çok rahat. Alıştığımız Türkiye şartlarından çok çok uzakta. Tek bir sınavları oluyor onda da gerçekten kalmak için adeta çaba göstermeniz gerekiyor. Derslerin de zaten hepsi İngilizce. Bu konuda Polonya'ya eğitim ve dersleri eşleyebilme açısından iyi bir puan veriyorum. *Puanım: 9/10*

**GENEL YAŞAM:** Lodz eski sanayii kentiymiş bir zamanlar. Bu bakımdan gelişmiş bir şehirdi ama nereye kadar gelişmiş... Ankara'da doğup büyümüş biri olarak açıkçası bana yetersiz geldi bu durum. Yapılacak ciddi manada pek bir şey yoktu. Okul zaten dağınık bir kampüse sahip. Lodz da küçük bir şehir. Her kısmında bir fakülte var ki inanın Hacettepe Üniversitesi'ni seçmemin temel sebebi genel bir kampüsü olmasıydı. Bu yüzdendir sanırım, okulun spor faaliyetleri veya hobi olarak seçebileceğiniz bir topluluk bulmak oldukça zor. Erasmus grupları olmasa, akşam yapılacak aktivitelerimiz, yarışmalarımız dahi olmasa, yaşam gerçekten çok tekdüze.

Onun dışında insanlar hakkında konuşacak olursam yaşıtımız olan, oranın yerlileri gayet sıcakkanlı, cana yakın. Çok da yardımlarını gördüm gerçekten, muazzam insanlar fakat diğer bir yandan 30+ yaş dediğimiz vakit Avrupa'nın genel olarak her yerinde karşılaştığım sıkıntıları burada da yaşadım. Dil anlama/konuşma yetersizliği, kendi milliyetinden olmayanı dışlama olmasa dahi gençler kadar cana yakın olmamaları. Bunu da kültüre bağlamak istiyorum. O kadar 5 ay kaldığım, insanıyla, yemeğiyle iç içe olduğum şehir hakkında kötü yorum yapmak istemiyorum. Genel anlamıyla havasıyla, insanıyla soğuk bir memleket. Onu da öyle kabul etmek lazım. *Puanım: 7/10*

**SEYAHAT:** Gelelim en zevkli kısma ki bunu söylemekten büyük haz duyuyorum. Şu ekonomide, şu genel anlamıyla dünyanın enflasyon gibi lanet bir belayla karşı karşıya olduğu dönemde 12 ülke 25 şehirde bulundum fakat gezip tadına, kültürüne baktığım ise 10 ülke 18 şehir oldu. Herkesin hayalinde temel bir amaç oluyor Erasmus'a gelirken. Benimki de seyahatti. Avrupa'ya ilk çıkışımdı ve gerçekten de aklımda, zihnimde biriktirdiğim neresi varsa gittim. Hatta bazılarına ikişer üçer kez gittim orası da ayrı bir durum. Muhteşemdi. Barcelona'da denize girmek, Bologna gibi 'Kızıl' bir şehirde devrim niteliğinde bir Pride yürüyüşüne katılmak, Berlin'de tekno club denemeleri, Amterdam'da legal olan ne varsa deneyip farklı bir boyuta geçtiğimiz anlar, Roma'da her kuytu köşede espresso içmek(bir daha granül kahve içemedim o günden sonra...). İnanılmazdı. Tek kelimeyle... inanılmazdı.

Tabii her güzel şeyin bir olumsuz tarafı da oluyor. Gezdiğim, gördüğüm yerlerde ne kadar dikkat etsem dahi sırf aynı dili konuşmadığımdan ki çatpat İspanyolca bilirim, İngilizce'me de gerçekten güvenirim fakat yerel dili konuşmadığınız takdirde sanki ülkelerine baskın yapmaya gelen mülteci konumuna düşüyorsunuz ki emin olun bu hissin tam tersini bir bakıma hepimiz Türkiye'de hissetmişizdir. Bunun karşı tarafında olmak, üstelik öğrenim görmeye gittiğiniz, bilginizle, çabanızla gittiğiniz bir yerlerde bu durumla karşılaşmak acayip rahatsız edici bir durum. Bu da minik bir uyarı olarak burada kalsın, denk gelirseniz şaşırmayınız.

Genel hatlarıyla seyahati de toparlayacak olursam Eyfel'e karşı sabahlamasından, trende, garda, havalimanında uyumasına kadar iyi-kötü tüm yönleriyle bana her dakika farklı bir şeyler katan bu konuya 10/10 vermek istiyorum. Bir daha olsa bir daha yaparım. Hayat kısa, görmek istediğiniz yerleri, deneyimlemek istediğiniz hayatları ertelemeyin. Kuş olun, uçun. *Puanım 10/10*

**ÖZET:** Polonya güzel bir ülke. Avrupa'da yaşamak da çok ayrı bir deneyim ancak gönül ister ki doğup büyüdüğüm yer de bu konumlarda olabilsin. Gerek ekonomisiyle gerek ifade özgürlüğüyle gerçek anlamda yaşadım, yaşadık diyebilelim. Atamızın ilkeleri önderliğinde, kendimiz geliştirmek için gerçekten çabalayalım. Biz bunu kendimiz yapmazsak kimse bizim için yapmayacak arkadaşlar. Kimse...

Son olarak kazanamayanlara başka programların da olduğunu, onları da denemelerini; kazananlara ise bolca tebrik ve canıgönülden keyifli bir Erasmus geçirmelerini temenni ederim.
