---
title: "Our Course Project"
sidebar: false 
---

I'm honored to be a member of the \[group name\] project team.

Below, you'll find a brief summary of our project. To access a detailed project description, please go to [https://\[https://emu-hacettepe-analytics.github.io/emu430-fall2023-team-team_safe_istanbul/l\]](https://emu-hacettepe-analytics.github.io/emu430-fall2023-team-team_safe_istanbul/){.uri}

**Summary**

\ We will utilize three datasets provided by the Istanbul Metropolitan Municipality.

The first dataset, titled “Earthquake Scenario Analysis Results”, contains the outcomes of analyses conducted based on a 7.5 Mw nighttime earthquake scenario.

The second dataset, “Neighborhood-Based Building Numbers in 2017”, comprises information on the number of buildings in Istanbul’s neighborhoods. These buildings are categorized by their construction year and the number of floors.

The third dataset is “Municipality Population in 2019”, contains population of Istanbul by districts in 2019.

Our objective is to compile a comprehensive report and identify the districts in Istanbul that are most susceptible to potential earthquakes. We aim to create an ordered priority list for neighborhoods and develop a risk map for Istanbul, taking geographical coordinates into account.\
